+----------------+                                +----------------+                             +----------------+
|     Client     |                                |   Person API   |                             |    Database    | 
+----------------+                                +----------------+                             +----------------+ 
        |                                                  |                                             |
        | HTTP Requests                                    |                                             | MongoDB
        |                                                  |                                             |  
+----------------+                                +------------------+                           +-----------------+
|     Routes     |                                |Person Controllers|                           |Person Collection| 
+----------------+                                +-----------------+                            +-----------------+ 
        |                                                  | get                                          |
        | Route Handling                                   | post                                         | 
        |                                                  | put, delete                                  |  
+----------------+                                +------------------+                           +----------------+
|     Models     |                                |     Database     |                           |     Methods    | 
+----------------+                                +------------------+                           +----------------+ 
        |                                                  |                                             | create
        |                                                  |                                             | findById
        |                                                  |                                             | update, remove
+----------------+                                +-----------------+                           +----------------+
|  Person Model  |                                |Person Collection|                           |Database Records| 
+----------------+                                +-----------------+                           +----------------+ 
        |                                                  |                                             |
        | Data Structure                                   |                                             | 
        |                                                  |                                             |  
+----------------+                                 +----------------+                           +----------------+
|   Attrubutes   |                                 |Database Records|                           |   Attrubutes   | 
+----------------+                                 +----------------+                           +----------------+ 
        |                                                  |                                             |
        | Entities                                         |                                             | 
        |                                                  |                                             |  
+----------------+                                 +----------------+                           +----------------+
|      name      |                                 |      name      |                           |      name      | 
+----------------+                                 +----------------+                           +----------------+ 
